### ISSUE TITLE
Migration to Vue.js 3.x?

### ISSUE THREAD

**Issue by D-T-666** [amp-up-io/qti3-item-player#6]
I want to use this component in a vue.js 3.x application but I'm running in trouble (because the component is implemented in 2.x). If I were to try to migrate the repo to 3.x, what would cause a problem? What will the challenges on the way look like?

**Comment by paulgrudnitski** [comment]
The qti3-item-player component has already been migrated to Vue 3.4.  It is available here:  [qti3-item-player-vue3](https://github.com/amp-up-io/qti3-item-player-vue3)

It took quite a bit longer (about 2 months instead of 2 weeks) to do the migration than I had expected.  Two challenges:

1.  The QTI 3 Item specification is BIG.  There are > 380 modules in the built component so it took time to inspect and touch and test/verify the proper working of that many modules.

2. The Vue 2.6 component makes extensive use of $children.  In Vue 3, $children is gone.  This required some thought and coherence around a new pattern to identify the children of each QTI subcomponent.

But...it's done now :)  Let me know what you think.

**Comment by D-T-666** [comment]
Oh... Amazing! I will be using that I guess. Thanks for your work! 🚀

**Comment by paulgrudnitski** [comment]
You're welcome!  I'm going to close this.
